version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run
        name: Install dependencies
        command:
          yarn
      - run
        name: run Unit Tests
        command:
          yarn Jest

workflows:
  build_test
    jobs:
      - run_tests